Update robot.md
Minor fix, which caused the error

AttributeError: 'coroutine' object has no attribute 'machine_part_id'
sys:1: RuntimeWarning: coroutine 'RobotClient.get_cloud_metadata' was never awaited